### ISSUE TITLE
When a TerminalView is embedded in an NSSplitView (macOS), the caretView position is not updated when the split view divider is dragged

### ISSUE THREAD

**Issue by mixio** [migueldeicaza/SwiftTerm#244] opened 2022-07-01 08:09 UTC
When a TerminalView is embedded in an NSSplitView (macOS), the caretView position is not updated when the split view divider is dragged.

One solution seems to be to add a notification observer to the TerminalView.setup() method:

```swift
// SwiftTerm/Sources/SwiftTerm/Mac/MacTerminalView.swift
private func setup()
{
    wantsLayer = true
    isBigSur = ProcessInfo.processInfo.isOperatingSystemAtLeast(OperatingSystemVersion(majorVersion: 11, minorVersion: 0, patchVersion: 0))
    if isBigSur {
        disableFullRedrawOnAnyChanges = true
    }
    setupScroller()
    setupOptions()
/*+++*/   // Added to update caretView's position on split view's divider drags.
/*+++*/   NotificationCenter.default.addObserver(forName: NSView.frameDidChangeNotification, object: self, queue: .main) { [weak self] _ in
/*+++*/       self?.updateDisplay()
/*+++*/   }
}
```

**Comment by migueldeicaza** [comment] 2022-07-09 12:43
Thanks for the bug report - it should be fixed now, please let me know if this works for you.

**Closed by migueldeicaza** 2022-07-09 12:43 UTC

**Comment by migueldeicaza** [comment] 2022-07-09 12:54
Thanks for this report!

I think the issue is that I am updating the position of the caret in two places, and they are slightly out of sync.

**Comment by mixio** [comment] 2022-07-09 15:11
Thanks Miguel, works as expected now.
