### ISSUE TITLE
User custom colors

### ISSUE THREAD

**Issue by SAPIENTechnologies** [migueldeicaza/SwiftTerm#106] opened 2020-05-01 20:24 UTC
It would be nice to allow the user to set custom background and foreground colors in iOS. I have tested this by modifying the Colors struct init as follows

`            public init(useSystemColors: Bool, foregroundColor: UIColor = UIColor.gray, backgroundColor: UIColor = UIColor.black) {
                self.useSystemColors = useSystemColors
                self.foregroundColor = foregroundColor
                self.backgroundColor = backgroundColor
            }
`

I don't see what the useSystemColors param does, but I have not gone extensively into the source yet.

**Comment by migueldeicaza** [comment] 2020-05-02 03:41
Agreed, it would be nice.

Currently the customization is done via an `option` parameter, but I think that we should instead make those independent properties, so `colorPalette`, `defaultForeground`, `defaultBackground`, `baseFont` and so on.

@krzyzanowskim originally did the option feature, before nothing could be changed :-)

**Comment by migueldeicaza** [comment] 2020-05-02 04:29
Closing, as this is a duplicate of #21

**Closed by migueldeicaza** 2020-05-02 04:29 UTC
