### ISSUE TITLE
Written text is not getting 

### ISSUE THREAD

**Issue by HardikMoon** [migueldeicaza/SwiftTerm#325] opened 2023-09-14 04:37 UTC
basically i need a entered text in terminal like if i type "ls" so when i click enter i need to get that whole entered text "ls".

As of now one one character i found but i need to get whole enter text.

Suggest me how to get it.

**Comment by migueldeicaza** [comment] 2023-09-14 18:34
This is not a bug, closing, use discussions for that.

**Closed by migueldeicaza** 2023-09-14 18:34 UTC
