### ISSUE TITLE
Messed up character width for some fonts

### ISSUE THREAD

**Issue by lukepistrol** [migueldeicaza/SwiftTerm#286] opened 2023-03-23 23:38 UTC
For some fonts the character width is a bit messed up (i.e. too wide).

SwiftTerm:

<img width="502" alt="Screenshot 2023-03-24 at 00 30 59" src="https://user-images.githubusercontent.com/9460130/227387135-b0748b53-bc12-45dc-a290-55862aff7f69.png">

Apple's Terminal (iTerm looks the same):

<img width="347" alt="Screenshot 2023-03-24 at 00 32 05" src="https://user-images.githubusercontent.com/9460130/227387164-d320d631-c679-4038-9dfc-cc8b630a2e57.png">

The font used in this example is [FiraCode](https://fonts.google.com/specimen/Fira+Code) but this happens with a couple of other fonts (Source Code Pro for Powerline, Fira Mono for Powerline) too which look totally normal in other Terminal emulators.

**Comment by migueldeicaza** [comment] 2023-04-17 00:34
This is odd, how did you get this setup?

**Comment by migueldeicaza** [comment] 2023-07-06 10:18
Folks, I could appreciate a complete bug report, something I can reproduce on my end.

Otherwise, I spend hours tracking down third party issues.   I am using those fonts and do not have that problem on iOS.

**Comment by scrapp08** [comment] 2023-08-29 20:56
Adding onto this, nerd fonts do not seem to render correctly.

What I'm getting:
<img width="921" alt="image" src="https://github.com/migueldeicaza/SwiftTerm/assets/105889363/4ed24c81-5547-40e7-9973-dfc6987c0591">


What is expected:
<img width="1485" alt="image" src="https://github.com/migueldeicaza/SwiftTerm/assets/105889363/3f8c9b3f-7751-4e7b-92a2-73d570758f99">

**Comment by jwells89** [comment] 2024-02-10 22:34
I’m seeing this issue with a few fonts as well.
<img width="687" alt="FontBug" src="https://github.com/migueldeicaza/SwiftTerm/assets/5009493/3c83f2b3-b5d3-4580-9bb9-68a36bfc7bc9">

Screenshot taken in my own project, but it’s reproducible in the MacTerminal sample project by:
1. Installing the attached version of the free Cascadia Code font
2. In `viewDidLoad()` in `ViewController.swift`, inserting `terminal.font = NSFont(name: "Cascadia Code", size: 13)!`
3. Running the app

I’m running macOS 14.3.1 (23D60) on an Apple Silicon machine. Let me know if there are any details I’ve missed, and if it would be helpful I can try to reproduce this in a clean VM to help rule out possibilities.

[CascadiaCode.zip](https://github.com/migueldeicaza/SwiftTerm/files/14230713/CascadiaCode.zip)

**Comment by austincondiff** [comment] 2024-06-13 22:02
I am still seeing this even when I am not using a nerd font.

<img width="816" alt="image" src="https://github.com/migueldeicaza/SwiftTerm/assets/806104/b413b768-dbc0-4ac3-909c-87cf1f137953">

**Comment by austincondiff** [comment] 2024-06-14 20:50
For what it's worth this has been a problem with the integrated terminal in VS Code in the past as you can see in [this issue](https://github.com/microsoft/vscode/issues/120004).

**Comment by evrensen467** [comment] 2024-07-21 09:53
Any update for this?

**Comment by austincondiff** [comment] 2024-07-29 01:36
@migueldeicaza any thoughts as to why this is happening? This continues to be a recurring issue that keeps getting brought up by our contributors/users.

**Comment by migueldeicaza** [comment] 2024-07-29 14:25
I have not had a chance to look into this, I am sadly juggling a lot of things this summer.

**Comment by thecoolwinter** [comment] 2024-08-01 18:47
I'm taking a look into this, it appears to be rooted in how SwiftTerm calculates the cell size for a font on macOS [here](https://github.com/migueldeicaza/SwiftTerm/blob/0f1cd2415e738bf20e894c62fe802725a9858d78/Sources/SwiftTerm/Apple/AppleTerminalView.swift#L149C9-L149C64).

To reproduce, the SF Mono font needs to be installed manually. I'm not sure yet why this causes the problem. SF Mono works fine when not installed manually but returns a much wider width otherwise.

**Comment by migueldeicaza** [comment] 2024-08-01 21:24
Oh very good catch - it seems like this would return the *largest* possible width of any of the characters on the set, which explains the problem, as these fonts likely contain glyphs from languages that use two cells (like Chinese characters, or Emoji).

So probably we need something like the "W" hack that is used for iOS, an option is:

```
https://developer.apple.com/documentation/appkit/nsfont/2887171-getadvancements?changes=_3
```

And we would pass all the ascii characters to it, and then get the maximum value out of those - for other characters, there is already special handling in the code for it.

**Comment by migueldeicaza** [comment] 2024-08-01 21:39
Could folks try this patch?

```
diff --git a/Sources/SwiftTerm/Apple/AppleTerminalView.swift b/Sources/SwiftTerm/Apple/AppleTerminalView.swift
index 35ce9ce..db1c404 100644
--- a/Sources/SwiftTerm/Apple/AppleTerminalView.swift
+++ b/Sources/SwiftTerm/Apple/AppleTerminalView.swift
@@ -146,7 +146,8 @@ extension TerminalView {
         let lineLeading = CTFontGetLeading (fontSet.normal)
         let cellHeight = ceil(lineAscent + lineDescent + lineLeading)
         #if os(macOS)
-        let cellWidth = fontSet.normal.maximumAdvancement.width
+        let glyph = font.glyph(withName: "W")
+        cellWidth = fontSet.normal.advancement(forGlyph: glyph)
         #else
         let fontAttributes = [NSAttributedString.Key.font: fontSet.normal]
         let cellWidth = "W".size(withAttributes: fontAttributes).width
```

**Comment by thecoolwinter** [comment] 2024-08-03 01:49
That patch fixes the issue. I did also implement the method you mentioned before with grabbing all ASCII characters and getting the max width. Looks like this:
```diff
diff --git a/Sources/SwiftTerm/Apple/AppleTerminalView.swift b/Sources/SwiftTerm/Apple/AppleTerminalView.swift
index 35ce9ce..0eb0900 100644
--- a/Sources/SwiftTerm/Apple/AppleTerminalView.swift
+++ b/Sources/SwiftTerm/Apple/AppleTerminalView.swift
@@ -146,7 +146,16 @@ extension TerminalView {
         let lineLeading = CTFontGetLeading (fontSet.normal)
         let cellHeight = ceil(lineAscent + lineDescent + lineLeading)
         #if os(macOS)
-        let cellWidth = fontSet.normal.maximumAdvancement.width
+        // Grab all non-control ascii characters and get the max width.
+        var sizes = UnsafeMutablePointer<NSSize>.allocate(capacity: 95)
+        let ctFont = (font as CTFont)
+        var glyphs = (32..<127).map { CTFontGetGlyphWithName(ctFont, String(Unicode.Scalar($0)) as CFString) }
+        withUnsafePointer(to: glyphs[0]) { glyphsPtr in
+            fontSet.normal.getAdvancements(NSSizeArray(sizes), forCGGlyphs: glyphsPtr, count: 95)
+        }
+        let cellWidth = (0..<95).reduce(into: 0) { partialResult, idx in
+            partialResult = max(partialResult, sizes[idx].width)
+        }
         #else
         let fontAttributes = [NSAttributedString.Key.font: fontSet.normal]
         let cellWidth = "W".size(withAttributes: fontAttributes).width
```

I found it didn't make a difference for the calculated with on a few different fonts I tried. It is much slower than grabbing a single glyph (about 0.21 in a rough benchmark vs too small to benchmark).

<details><summary>Bechmark code</summary>
<p>
I wanted to make sure this wouldn't affect performance.

```zsh
% swiftc main.swift -o a -Onone && ./a
0.21186870669999877 ms
```
```swift
import Foundation
import AppKit

@_optimize(none)
public func blackHole(_: some Any) {}

var times: [TimeInterval] = []

for _ in 0..<10_000 {
    let font = NSFont.monospacedSystemFont(ofSize: 12, weight: .regular)

    var info = mach_timebase_info()
    guard mach_timebase_info(&info) == KERN_SUCCESS else { exit(1) }
    let start = mach_absolute_time()

    let sizes = UnsafeMutablePointer<NSSize>.allocate(capacity: 95)
    let ctFont = (font as CTFont)
    let glyphs = (32..<127).map { CTFontGetGlyphWithName(ctFont, String(Unicode.Scalar($0)) as CFString) }
    withUnsafePointer(to: glyphs[0]) { glyphsPtr in
        font.getAdvancements(NSSizeArray(sizes), forCGGlyphs: glyphsPtr, count: 95)
    }
    let cellWidth = (0..<95).reduce(into: 0) { partialResult, idx in
        partialResult = max(partialResult, sizes[idx].width)
    }
    blackHole(cellWidth)

    let end = mach_absolute_time()
    let elapsed = end - start
    let nanos = elapsed * UInt64(info.numer) / UInt64(info.denom)
    times.append(TimeInterval(nanos) / TimeInterval(NSEC_PER_MSEC))
}

print(times.reduce(0, +) / Double(times.count), "ms")
```

</p>
</details> 

I'd be happy to make either of these into a PR. Which one would you prefer?

**Comment by migueldeicaza** [comment] 2024-08-03 21:41
Let us go with my version then, to avoid the startup penalty.

Thank you!

**Comment by thecoolwinter** [comment] 2024-08-07 23:10
Opened that up, was out of town for a few days sorry for the delay!

**Comment by migueldeicaza** [comment] 2024-08-08 20:24
Closing

**Closed by migueldeicaza** 2024-08-08 20:24 UTC
